version: 1.0.{build}

branches:
  only:
    - master

skip_tags: false

skip_non_tags: false

max_jobs: 1

image: Visual Studio 2019

platform: Any CPU

configuration:
  - Debug
  - Release

build:
  parallel: true
  project: error-analysis-test.sln
  publish_core_console: true
